from typing import Any, Protocol


class TrackingHandle(Protocol):
    def track_metric(self, step: int, note: str | None = None, **metrics): ...
    def track_artifact(self, data: Any, step: int | None = None,
                        group: str | None = None, name: str = '', type: str = 'pickle'): ...
    def load_artifact(self, group: str | None = None, name: str = '',
                       step: int | None = None, type: str = 'pickle') -> Any: ...
    def get_logger(self, **kwargs): ...
    def finalize(self): ...
    def set_status(self, **kwargs): ...
    run_id: str
    run_dir: Any


class ControlHandle(Protocol):

    def send_command(self, cmd: dict): ...
    def poll_commands(self) -> list[dict]: ...

    # def set_status(self, **kwargs): ...
    # def get_status(self) -> dict: ...   
    #  # def get_status(self) -> dict: ...