"""
Structural contract between rewind and whatever tracking library is used.

TrainerController is written against this, never against tracklab directly.
That's what keeps loopctl reusable across projects and even across tracking
libraries -- swapping tracklab for something else later means writing one
new adapter, not touching controller.py.
"""

from typing import Any, Protocol


class RunHandle(Protocol):
    def track_metric(self, step: int, note: str | None = None, **metrics): ...
    def track_artifact(self, data: Any, step: int | None = None, name: str = '', type: str = 'pickle'): ...
    def load_artifact(self, name: str = '', step: int | None = None, type: str = 'pickle') -> Any: ...
    def get_logger(self, **kwargs): ...
    def finalize(self): ...

    # not part of tracklab.Run itself -- added by the adapter, see
    # tracklab_adapter.py. Included here because the controller needs them.
    def set_status(self, **kwargs): ...
    def get_status(self) -> dict: ...
    def send_command(self, cmd: dict): ...
    def poll_commands(self) -> list[dict]: ...