"""rewind/dashboard/app.py

Assembles the App from the panel modules. This is deliberately the *only*
file that has to know about every panel at once -- each module above is
independently understandable, and independently testable, without it.

Reactivity design: one shared `reactive.poll` per active run (metrics +
status), memoized per run_dir, feeding every downstream panel. Panels never
read files themselves; they take a callable/reactive.Calc and render it.
"""

from __future__ import annotations

import dataclasses
import json
from pathlib import Path

from shiny import App, reactive, ui

from tracklab import ExperimentReader
from tracklab.live import MetricsStream

from .config import DashboardConfig, RunContext
from .schema import form_fields
from ..launch import RunLauncher
from ..control import RunMailbox
from .._layout import status_path
from .modules import control_panel, experiment_picker, launcher_form, metrics_panel, runs_table

# Keyed by run_dir. A MetricsStream tracks a byte offset internally, so it
# must be reused across polls rather than reconstructed every tick, or every
# poll would silently re-read the whole file from the start. A module-level
# cache is a deliberate simplification for a local, single-session tool --
# revisit if this ever needs to serve multiple concurrent Shiny sessions.
_stream_cache: dict[Path, MetricsStream] = {}


def _get_stream(run_dir: Path) -> MetricsStream:
    if run_dir not in _stream_cache:
        _stream_cache[run_dir] = MetricsStream(run_dir)
    return _stream_cache[run_dir]


def build_dashboard(cfg: DashboardConfig) -> App:
    """Build a ready-to-run Shiny `App` for a project, from a single
    `DashboardConfig`.

    This is the one function a project needs to call to get the full
    baseline dashboard -- experiment picker, an auto-generated launch form,
    a runs table, a live metrics view, and a control panel driven entirely
    by whatever a run's `actions.json` declares. Nothing about this function
    is project-specific; everything project-specific comes in through `cfg`.

    Parameters
    ----------
    cfg : DashboardConfig
        base_dir         Root folder experiments are read from / written
                          under (e.g. "./data"). Created if it doesn't exist.
        config_cls        The project's config dataclass (e.g. TrainerArgs).
                          Introspected by schema.form_fields() to build the
                          launch form -- must be a (possibly nested) stdlib
                          dataclass, not a plain dict or a Pydantic model.
        entrypoint         `python -m <entrypoint> ...` target RunLauncher
                          invokes to start a run, e.g. "my_project.launcher".
        field_overrides    Optional. {dotted_field_path: widget_fn} for the
                          rare field that shouldn't get its default widget
                          (see schema.input_id for the id contract a custom
                          widget_fn must follow).
        extensions          Optional. list[DashboardExtension] -- custom
                          tabs for anything that doesn't fit the generic
                          form/plot mold (see config.DashboardExtension).
        poll_interval_s      How often the shared live poll re-reads the
                          active run's metrics/status. Default 1.0s.

    Returns
    -------
    shiny.App
        Assign this to a module-level `app` variable in a script and run it
        with `shiny run --reload path/to/script.py`, e.g.:

            # my_project/scripts/dashboard.py
            from rewind.dashboard import build_dashboard, DashboardConfig
            from my_project.config import TrainerArgs

            app = build_dashboard(DashboardConfig(
                base_dir="./data",
                config_cls=TrainerArgs,
                entrypoint="my_project.launcher",
            ))

    Raises
    ------
    TypeError
        If `config_cls` isn't a dataclass -- schema.form_fields() would
        otherwise fail deep inside a render function instead of here, at
        the one point where the mistake is easy to trace.
    ValueError
        If `entrypoint` is empty, or any `field_overrides` key doesn't
        correspond to a real field on `config_cls` (a typo here would
        otherwise silently do nothing -- the override just never triggers).
    """
    cfg.base_dir = Path(cfg.base_dir)
    cfg.base_dir.mkdir(parents=True, exist_ok=True)

    if not dataclasses.is_dataclass(cfg.config_cls):
        raise TypeError(
            f"DashboardConfig.config_cls must be a dataclass, got {cfg.config_cls!r}. "
            "The launch form is generated by introspecting its fields via "
            "dataclasses.fields()."
        )
    if not cfg.entrypoint:
        raise ValueError("DashboardConfig.entrypoint must be a non-empty 'python -m' target.")

    valid_paths = {f.path for f in form_fields(cfg.config_cls)}
    unknown_overrides = set(cfg.field_overrides) - valid_paths
    if unknown_overrides:
        raise ValueError(
            f"field_overrides references unknown field(s): {sorted(unknown_overrides)}. "
            f"Known fields: {sorted(valid_paths)}"
        )

    app_ui = ui.page_fluid(
        ui.h2("Rewind"),
        ui.layout_sidebar(
            ui.sidebar(
                experiment_picker.experiment_picker_ui("exp"),
                launcher_form.launcher_form_ui("launch", cfg),
                width=380,
            ),
            ui.navset_tab(
                ui.nav_panel("Runs", runs_table.runs_table_ui("runs")),
                ui.nav_panel("Live", metrics_panel.metrics_panel_ui("metrics")),
                ui.nav_panel("Control", control_panel.control_panel_ui("control")),
                *[ui.nav_panel(ext.label, ext.ui()) for ext in cfg.extensions],
            ),
        ),
    )

    def server(input, output, session):
        selected_experiment = experiment_picker.experiment_picker_server("exp", cfg.base_dir)

        # The run currently being watched. Set when a launch succeeds; could
        # also be set by selecting an existing run from the Runs tab -- left
        # as a follow-up, not needed for the baseline.
        active_launcher: reactive.Value[RunLauncher | None] = reactive.value(None)

        def _on_launched(launcher: RunLauncher) -> None:
            active_launcher.set(launcher)

        launcher_form.launcher_form_server("launch", cfg, selected_experiment, _on_launched)

        @reactive.calc
        def active_run_dir() -> Path | None:
            launcher = active_launcher.get()
            exp_name = selected_experiment()
            if launcher is None or launcher.record is None or not exp_name:
                return None
            return cfg.base_dir / exp_name / launcher.record.run_id

        @reactive.calc
        def reader() -> ExperimentReader:
            exp_name = selected_experiment() or ""
            return ExperimentReader(exp_name, base_dir=cfg.base_dir)

        # ---- single shared poll; every panel below derives from this ----
        @reactive.poll(lambda: _poll_once(active_run_dir()), cfg.poll_interval_s)
        def live_data() -> dict:
            # reactive.poll only invalidates downstream reactives when the
            # returned value actually changes, so this is the one place any
            # disk I/O for the active run happens per tick -- not once per
            # panel.
            return _poll_once(active_run_dir())

        runs_table.runs_table_server("runs", reader)
        metrics_panel.metrics_panel_server("metrics", lambda: live_data()["metrics"])
        control_panel.control_panel_server("control", active_run_dir)

        @reactive.calc
        def active_mailbox() -> RunMailbox | None:
            rd = active_run_dir()
            return RunMailbox(rd) if rd else None

        for ext in cfg.extensions:
            # Pass the reactive.Calc objects themselves, not their called
            # results -- so ctx.run_dir() etc. stay live inside whatever the
            # extension renders, instead of freezing at whatever was active
            # when the app started. See RunContext's docstring.
            ctx = RunContext(reader=reader, run_dir=active_run_dir, mailbox=active_mailbox)
            ext.server(input, output, session, ctx=ctx)

    return App(app_ui, server)


# def _poll_once(run_dir: Path | None) -> dict:
#     if run_dir is None:
#         return {"metrics": None, "status": None}
#     stream = _get_stream(run_dir)
#     # status.json is Rewind's file now (rewind/control/status.json), not
#     # TrackLab's -- read it directly rather than through MetricsStream,
#     # which only knows about metrics.jsonl.
#     sp = status_path(run_dir)
#     # status = json.loads(sp.read_text()) if sp.exists() else None
#     try:
#         status = json.loads(sp.read_text()) if sp.exists() else None
#     except (FileNotFoundError, json.JSONDecodeError):
#         status = None
#     return {"metrics": stream.poll(), "status": status}

def _poll_once(run_dir: Path | None) -> dict:
    if run_dir is None:
        return {"metrics": None, "status": None}
    stream = _get_stream(run_dir)
    sp = status_path(run_dir)
    try:
        status = json.loads(sp.read_text()) if sp.exists() else None
    except (FileNotFoundError, json.JSONDecodeError):
        status = None

    metrics_df = stream.poll()
    metrics = metrics_df.to_dict("records")  # list[dict] -- comparable, satisfies reactive.poll
    return {"metrics": metrics, "status": status}